### ISSUE TITLE
Change FirstYear based on a variable

### ISSUE THREAD

**Issue by banjee77** [nikitsky/heatmap_calendar_apex_plugin#4]
Hi Valentine,

is there a way to change firstYear and refresh the heatmap within APEX?

Regards,
Banthu

**Comment by nikitsky** [comment]
Hi,

Yes, it is possible, you can see it in action on the demo https://apex.oracle.com/pls/apex/f?p=113960

You can use an page item on the first year plugin attribute:
<img width="1043" alt="banners_and_alerts_and_page_designer" src="https://user-images.githubusercontent.com/2596018/35980986-6b87f75a-0cec-11e8-99ef-7d1d7676ebb7.png">

All the best,
Valentine
